# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'UIPathOrchestratorS'
    packagesPath: 'C:\Users\vinita.rai\.nuget\packages\uipath\20.6.7473.25550-preview'
    folderName: 'Default'